export const marksMapping = {
    '8 kyu': 1,
    '7 kyu': 1,
    '6 kyu': 4,
    '5 kyu': 5,
    '4 kyu': 10,
    '3 kuy': 15,
    '1 kuy': 20
}

export const targetKatas = [
  "Opposite number",
  "Basic Mathematical Operations",
  "Printing Array elements with Comma delimiters",
  "Transportation on vacation",
  "Get the Middle Character",
  "Partition On",
  "Word Count",
  "Remove First and Last Character Part Two",
  "Implement a Filter function",
  "Prefill an Array",
  "Cross Product of Vectors",
  "Sequence generator",
  "Base Conversion",
  "Closures and Scopes",
  "A function within a function",
  "Can you keep a secret?",
  "Using closures to share class state",
  "A Chain adding function",
  "Function Cache",
  "Function Composition",
  "Function Composition",
  "Stringing me along",
  "I Spy",
  "Calculating with Functions",
  "SantaClausable Interface",
  "new with apply",
  "Extract Nested Object Reference",
  "Array Helpers",
  "Replicate `new`",
  "Sum of Digits / Digital Root",
  "Fun with ES6 Classes #2 - Animals and Inheritance Fun with ES6",
  "Classes #3 - Cuboids, Cubes and Getters",
  "Lazy evaluation",
  "Tail recursion with trampoline",
  "Functional SQL",
  "Can you get the loop?"
]