service:
  name: karate-scraper
plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpackIncludeModules: true
  prefix: ${self:service}-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}
  task_table: ${self:custom.prefix}-task
  isVersionFunctions-prod: true
  isVersionFunctions-default: false
  start:
    seed: true
    inMemory: true
  task_stream: ${file(./config.env.local.yml):task_stream}

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: test
  deploymentBucket: karate-sls-deploys
  versionFunctions: ${self:custom.isVersionFunctions-${self:custom.stage}, self:custom.isVersionFunctions-default}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.task_table}
  environment:
    region: ${self:provider.region}
    stage: ${self:custom.stage}
    task_table: ${self:custom.task_table}

functions:
  scrape:
    handler: handler.scrape
    timeout: 300
    memorySize: 1536
    events:
      - stream: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.task_table}/stream/${self.custom:task_stream}

  addTask:
    handler: handler.addTask
    events:
      - http:
          method: post
          path: tasks
          cors: true

  getResult:
    handler: handler.getResult
    events:
      - http:
          method: get
          path: results/{id}
          cors: true

  findExpression:
    handler: handler.findExpression
    events:
      - http:
          method: post
          path: expression
          cors: true

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.task_table}
        KeySchema:
          -
            AttributeName: task_id
            KeyType: HASH
          -
            AttributeName: timestamp
            KeyType: RANGE
        AttributeDefinitions:
          -
            AttributeName: task_id
            AttributeType: S
          -
            AttributeName: timestamp
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        TimeToLiveSpecification:
          AttributeName: timestamp
          Enabled: true
